language: node_js
node_js: node
cache:
  directories:
    - node_modules
notifications:
  email: false
install:
  - npm i
  - npm i -g codecov
script:
  - npm run $BUILD_NPM_SCRIPT

env:
  - BUILD_NPM_SCRIPT=unit-ci
  - BUILD_NPM_SCRIPT=lint

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8e560925f01de3f7be16
    on_success: always
    on_failure: always
    on_start: always
